"""
Shared list of job titles used by multiple API ingestion scripts.

All job title lists are defined only in this file. No other file or API defines or sources job title lists.

Used by: adzuna_top_jobs_to_mongo, adzuna_fetch_top_jobs, jobicy_fetch_top_jobs, jobicy_to_mongo, serpapi_fetch_top_jobs, serpapi_to_mongo.
Single source of truth; edit here to add/remove titles for all consumers.
"""

TOP_JOBS = [
    "Registered Nurse",
    "Software Developer",
    "Software Engineer",
    "Application Developer",
    "Backend Developer",
    "Frontend Developer",
    "Home Health Aide",
    "Personal Care Aide",
    "Truck Driver",
    "CDL Driver",
    "Heavy Truck Driver",
    "Commercial Driver",
    "Data Scientist",
    "Cybersecurity Analyst",
    "Information Security Analyst",
    "Security Analyst",
    "AI Engineer",
    "Artificial Intelligence Engineer",
    "Machine Learning Engineer",
    "Nurse Practitioner",
    "Financial Manager",
    "Physical Therapist",
    "Teacher",
    "K-12 Teacher",
    "Elementary School Teacher",
    "High School Teacher",
    "Electrician",
    "Licensed Electrician",
    "Delivery Driver",
    "Light Truck Driver",
    "Courier",
    "Sales Representative",
    "Account Executive",
    "Sales Associate",
    "Operations Manager",
    "General Manager",
    "Medical Services Manager",
    "Health Services Manager",
    "Healthcare Administrator",
    "Logistics Specialist",
    "Logistician",
    "Supply Chain Analyst",
    "Customer Service Representative",
    "Call Center Representative",
    "Support Specialist",
    "Wind Turbine Technician",
    "Wind Technician",
    "Solar Installer",
    "Solar Panel Installer",
    "Photovoltaic Installer",
    "Insurance Agent",
    "Insurance Sales Agent",
    "Security Guard",
    "Operations Research Analyst",
    "OR Analyst",
    "Management Consultant",
    "Management Analyst",
    "Maintenance Technician",
    "Service Technician",
    "Facilities Technician",
]
